version: '3'

services:
  database_1:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: permify
      POSTGRES_PASSWORD: permify
      POSTGRES_DB: permify
    ports:
      - "5432:5432"
    volumes:
      - postgres_1_data:/var/lib/postgresql/data
    networks:
    - permify_net


  database_2:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: permify
      POSTGRES_PASSWORD: permify
      POSTGRES_DB: permify
    ports:
      - "5432"
    volumes:
      - postgres_2_data:/var/lib/postgresql/data
    networks:
    - permify_net


  permify_1:
    image: permify/permify
    ports:
      - "3476:3476"
      - "3478:3478"

    command:
        - "serve"
        - "--database-auto-migrate=true"
        - "--database-engine=postgres"
        - "--database-uri=postgres://permify:permify@database_1:5432/permify"
        - "--tracer-exporter=zipkin"
        - "--tracer-endpoint=http://zipkin:9411/api/v2/spans"
        - "--tracer-enabled=true"
        - "--distributed-enabled=true"
        - "--distributed-node=serf:7946"
        - "--distributed-node-name=main-serf"
        - "--distributed-protocol=serf"

    #command: "serve --database-auto-migrate=true --database-engine=postgres --database-uri=postgres://root:root@cockroachdb:26257/permify --tracer-exporter=zipkin --tracer-endpoint=http://zipkin:9411/api/v2/spans --tracer-enabled=true "
    depends_on:
      - database_1
      #- cockroachdb
      - zipkin
      - serf
    networks:
     - permify_net

  permify_2:
    image: permify/permify
    ports:
      - "3477:3476"
      - "3479:3478"

    command:
        - "serve"
        - "--database-auto-migrate=true"
        - "--database-engine=postgres"
        - "--database-uri=postgres://permify:permify@database_2:5432/permify"
        - "--tracer-exporter=zipkin"
        - "--tracer-endpoint=http://zipkin:9411/api/v2/spans"
        - "--tracer-enabled=true"
        - "--distributed-enabled=true"
        - "--distributed-node=serf:7946"
        - "--distributed-node-name=main-serf"
        - "--distributed-protocol=serf"

    depends_on:
      - database_2
      #- cockroachdb
      - zipkin
      - serf
    networks:
     - permify_net

  serf:
    image: dweomer/serf
    command: "agent -node=serf -bind=0.0.0.0:7946 -rpc-addr=0.0.0.0:7373"
    ports:
     - "7946:7946"
     - "7373:7373"
    networks:
     - permify_net

  zipkin:
    hostname: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - permify_net

  
networks:
  permify_net:

volumes:
  postgres_1_data:
  postgres_2_data:
