version: '3'

services:
    permify_1:
        image: permify/permify
        ports:
        - "3476:3476"
        - "3478:3478"

        command:
            - "serve"
            - "--distributed-enabled=true"
            - "--distributed-node=serf:7946"
            - "--distributed-node-name=permify-1"
            - "--distributed-protocol=serf"

    #command: "serve --database-auto-migrate=true --database-engine=postgres --database-uri=postgres://root:root@cockroachdb:26257/permify --tracer-exporter=zipkin --tracer-endpoint=http://zipkin:9411/api/v2/spans --tracer-enabled=true "
        depends_on:
            - serf
        networks:
            - permify_net

    permify_2:
        image: permify/permify
        ports:
        - "3477:3476"
        - "3479:3478"

        command:
            - "serve"
            - "--distributed-enabled=true"
            - "--distributed-node=serf:7946"
            - "--distributed-node-name=permify-2"
            - "--distributed-protocol=serf"

        depends_on:
            - serf
        networks:
            - permify_net

    serf:
        image: dweomer/serf
        command: "agent -node=serf -bind=0.0.0.0:7946 -rpc-addr=0.0.0.0:7373"
        ports:
            - "7946:7946"
            - "7373:7373"
        networks:
            - permify_net

networks:
  permify_net:
